export type CardType = 'creature' | 'spell'

// Status effects that can be applied to creatures
export type StatusEffect =
  | 'frozen'      // Cannot attack next turn
  | 'poisoned'    // Takes 1 damage at start of each turn
  | 'taunt'       // Must be attacked before hero
  | 'stealth'     // Cannot be targeted until it attacks
  | 'silenced'    // Abilities disabled
  | 'doomed'      // Destroyed at end of turn

export type CardEffect =
  | { type: 'transform_into_creature' }  // Copy a creature on the field

export type Card = {
  id: string
  name: string
  flavor: string
  cost: number
  type: CardType
  image?: string
  baseStats?: {
    attack: number
    health: number
  }
  // Token creatures are generated by effects, not part of deck
  isToken?: boolean
  effect?: CardEffect
}

export type Creature = Card & {
  instanceId: string
  currentHealth: number
  currentAttack: number
  canAttack: boolean
  // New properties for expanded mechanics
  shield?: number              // Absorbs damage before health
  statusEffects?: StatusEffect[]  // Active status effects
  originalOwner?: 'player' | 'opponent'  // For stolen creatures
}

export type PlayerState = {
  health: number
  mana: number
  maxMana: number
  hand: Card[]
  deck: Card[]
  field: Creature[]
}

export type GameEvent = {
  turn: number
  actor: 'player' | 'opponent' | 'system'
  narrative: string
  timestamp: number
}

export type GameState = {
  turn: number
  currentPlayer: 'player' | 'opponent'
  player: PlayerState
  opponent: PlayerState
  log: GameEvent[]
  phase: 'playing' | 'resolving' | 'combat' | 'ended'
  winner?: 'player' | 'opponent'
}

export type StateChange = {
  type:
    // Existing effects
    | 'damage'           // Deal damage to target
    | 'heal'             // Restore health to target
    | 'destroy'          // Instantly destroy creature
    | 'buff'             // Increase creature stats
    | 'draw'             // Draw cards
    // Newly implemented
    | 'summon'           // Summon a token creature
    | 'discard'          // Discard cards from hand
    // Mana effects
    | 'gain_mana'        // Gain temporary mana this turn
    | 'steal_mana'       // Steal mana from opponent
    | 'modify_max_mana'  // Change max mana permanently
    // Debuffs
    | 'debuff'           // Reduce creature stats (separate attack/health)
    // Status effects
    | 'apply_status'     // Apply a status effect
    | 'remove_status'    // Remove a status effect
    // Defense
    | 'add_shield'       // Add shield to creature
    // Mill/Discard
    | 'mill'             // Remove cards from top of deck
    // Steal
    | 'steal_creature'   // Take control of enemy creature
    // Transform
    | 'transform'        // Change creature into another (or copy via sourceId)
    // Copy
    | 'copy_creature'    // Create copy of a creature
    // Bounce
    | 'bounce'           // Return creature to owner's hand
  target: 'player' | 'opponent' | 'creature'
  targetId?: string  // Creature being transformed (for 'transform') or targeted
  sourceId?: string  // Creature to copy from (for Mirror Mimic transform)
  value?: number
  // For buff/debuff - separate attack and health values
  attack?: number
  health?: number
  // For summon/transform/copy
  card?: Card
  // For status effects
  status?: StatusEffect
}

export type ResolveResponse = {
  narrative: string
  changes: StateChange[]
}

export type AITurnResponse = {
  action: 'play' | 'attack' | 'end_turn'
  cardIndex?: number
  attackerId?: string
  targetId?: string
  narrative: string
}

export type CreatureActionResponse = {
  action: 'attack_creature' | 'attack_hero' | 'special'
  targetId?: string
  narrative: string
  changes?: StateChange[]
}
