export type CardType = 'creature' | 'spell'

// Targeting types for spells
export type TargetType =
  | 'none'              // No target needed (affects board generally)
  | 'any_creature'      // Can target any creature on the board
  | 'enemy_creature'    // Can only target enemy creatures
  | 'friendly_creature' // Can only target friendly creatures
  | 'any_hero'          // Can target any hero
  | 'enemy_hero'        // Can only target enemy hero

// Status effects that can be applied to creatures
export type StatusEffect =
  | 'frozen'      // Cannot attack next turn
  | 'poisoned'    // Takes 1 damage at start of each turn
  | 'taunt'       // Must be attacked before hero
  | 'stealth'     // Cannot be targeted until it attacks
  | 'silenced'    // Abilities disabled
  | 'doomed'      // Destroyed at end of turn

export type Card = {
  id: string
  name: string
  flavor: string
  type: CardType
  image?: string
  baseStats?: {
    attack: number
    health: number
  }
  // Token creatures are generated by effects, not part of deck
  isToken?: boolean
  // Targeting for spells - defaults to 'none' if not specified
  targetType?: TargetType
}

export type Creature = Card & {
  instanceId: string
  currentHealth: number
  currentAttack: number
  canAttack: boolean
  // New properties for expanded mechanics
  shield?: number              // Absorbs damage before health
  statusEffects?: StatusEffect[]  // Active status effects
  originalOwner?: 'player' | 'opponent'  // For stolen creatures
}

export type PlayerState = {
  health: number
  hand: Card[]
  deck: Card[]
  field: Creature[]
}

export type GameEvent = {
  turn: number
  actor: 'player' | 'opponent' | 'system'
  narrative: string
  timestamp: number
}

export type GameState = {
  turn: number
  currentPlayer: 'player' | 'opponent'
  player: PlayerState
  opponent: PlayerState
  log: GameEvent[]
  phase: 'playing' | 'resolving' | 'combat' | 'ended'
  winner?: 'player' | 'opponent'
  hasPlayedCard: boolean  // Track if current player has played their one card this turn
}

export type StateChange = {
  type:
    // Existing effects
    | 'damage'           // Deal damage to target
    | 'heal'             // Restore health to target
    | 'destroy'          // Instantly destroy creature
    | 'buff'             // Increase creature stats
    | 'draw'             // Draw cards
    // Newly implemented
    | 'summon'           // Summon a token creature
    | 'discard'          // Discard cards from hand
    // Debuffs
    | 'debuff'           // Reduce creature stats (separate attack/health)
    // Status effects
    | 'apply_status'     // Apply a status effect
    | 'remove_status'    // Remove a status effect
    // Defense
    | 'add_shield'       // Add shield to creature
    // Mill/Discard
    | 'mill'             // Remove cards from top of deck
    // Steal
    | 'steal_creature'   // Take control of enemy creature
    // Transform
    | 'transform'        // Change creature into another
    // Copy
    | 'copy_creature'    // Create copy of a creature
    // Bounce
    | 'bounce'           // Return creature to owner's hand
  target: 'player' | 'opponent' | 'creature'
  targetId?: string
  value?: number
  // For buff/debuff - separate attack and health values
  attack?: number
  health?: number
  // For summon/transform/copy
  card?: Card
  // For status effects
  status?: StatusEffect
}

export type ResolveResponse = {
  narrative: string
  changes: StateChange[]
}

// Target selection for spells
export type SpellTarget = {
  type: 'creature' | 'hero'
  creatureId?: string      // instanceId if targeting a creature
  who?: 'player' | 'opponent'  // for hero targets
}

export type AITurnResponse = {
  action: 'play' | 'pass'
  cardIndex?: number
  narrative: string
}

export type CombatPhaseResponse = {
  narrative: string
  attacks: Array<{
    attackerId: string
    targetId: string | 'hero'  // 'hero' means attack the enemy hero
  }>
}

export type CreatureActionResponse = {
  action: 'attack_creature' | 'attack_hero' | 'special'
  targetId?: string
  narrative: string
  changes?: StateChange[]
}
